name: 'Cache Static Map Images'
on:
  workflow_dispatch:
  push:
    branches:
      - preview
jobs:
  Cache-Static-Maps:
    name: 'Cache Static Maps'
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: yarn install
      - name: Run map caching script
        run: |
          yarn content:cache-static-map-urls
        env:
          PUBLIC_MAPBOX_STYLE: ${{ secrets.PUBLIC_MAPBOX_STYLE }}
          STATIC_MAPBOX_TOKEN: ${{ secrets.STATIC_MAPBOX_TOKEN }}
          CLOUDINARY_URL: ${{ secrets.CLOUDINARY_URL }}
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: '[Bot] Cache static maps'
          commit_user_name: Sean C Davis
          commit_user_email: scdavis41@gmail.com
          commit_author: Sean C Davis <scdavis41@gmail.com>
          branch: ${{ github.head_ref }}
